# Site
name: 'Carlos Guerrero'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'guerrerocarlos@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    carlos:
      name:           Jane
      site:           https://www.carlosguerrero.com
      avatar:         https://avatars2.githubusercontent.com/u/82532?s=100
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          guerrerocarlos@gmail.com
      twitter:        https://twitter.com/guerrerocarlos

    sal:
      name:           Sal
      site:           https://www.carlosguerrero.com
      avatar:         https://avatars2.githubusercontent.com/u/82532?s=100
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          guerrerocarlos@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://www.carlosguerrero.com
      avatar:         https://avatars2.githubusercontent.com/u/82532?s=100
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          guerrerocarlos@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
